### ISSUE TITLE
Create ws for getting users by role and capabilities

### ISSUE THREAD

**Issue by guillogo** [aspiredu/moodle-local_aspiredu#17]
Create web services to retrieve users by roles or capabilities. 

(This issue refers to requirement: **2. Identify admins via permissions in Moodle.**)

**Comment by guillogo** [comment]
Hi @tim-schilling 

I have created this PR https://github.com/aspiredu/moodle-local_aspiredu/pull/18 to solve this issue.

This PR introduce 2 new ws in the plugin to get a paginated list of users given a list of roles or a list of capabilities based on this requirement sent by you:

_
> 2. Identify admins via permissions in Moodle
> 
> Today we ask our clients to put administrator users into a specific cohort that we then grant access to, specifically in our products.
> 
> We would like to be able to find an existing set of standard permissions to check and fetch users who meet those permissions.
> 
> It's not technical system administrators, but rather administrators in the organization who should have access to Dropout Detective. Kim let me know that there are two permissions, local/aspiredu:viewdropoutdetective and local/aspiredu:viewinstructorinsight that we've created in the past. Ideally, we'd be able to fetch the users with those permissions.
> 
> Regarding 2.
> 
> Sorry, one more to add to the list. Since we're not quite sure how to best integrate with Moodle client systems I'm a bit unsure on how to identify these users. Would it be possible to fetch a paginated list of users that have a given role?
_


**How to use them:**
e.g.: get_users_by_capabilities

`{your moodle}/webservice/rest/server.php?wstoken=xxxxx&wsfunction=local_aspiredu_get_users_by_capabilities&moodlewsrestformat=json&capabilities[0]=local/aspiredu:viewdropoutdetective&capabilities[1]=local/aspiredu:viewinstructorinsight` 

e.g.: get_users_by_roles
`{your moodle}webservice/rest/server.php?wstoken=xxxxx&wsfunction=local_aspiredu_get_users_by_roles&moodlewsrestformat=json&roleids[0]=5&roleids[1]=2`

**Comment by guillogo** [comment]
Also, pagination is available sending page and records per page e.g.: `&page=1$perpage=100`

**Comment by tim-schilling** [comment]
That sounds good. I'll update you when I've tested this on my end.
