### ISSUE TITLE
Create paginated course list API function to replace core_course_get_courses

### ISSUE THREAD

**Issue by guillogo** [aspiredu/moodle-local_aspiredu#19]
Create paginated course list API function to replace core_course_get_courses

A school had so many courses, their API would not return. Let's build a paginated version to avoid timeouts due to massive amounts of courses (30k)

(This issue refers to requirement: **4. Create paginated course list API function to replace core_course_get_courses**)

**Comment by guillogo** [comment]
Hi @tim-schilling

In the same PR https://github.com/aspiredu/moodle-local_aspiredu/pull/18 as Issue #17 I have added a commit to solve this issue.

The new commit introduce 1 new ws in the plugin to get a paginated list of courses given a list of courses ids or nothing to get all courses paginated.

**How to use it:**
All the courses paginated
 `{your moodle}/webservice/rest/server.php?wstoken=xxxxx&wsfunction=local_aspiredu_get_courses&moodlewsrestformat=json&page=0&perpage=10`

or specific courses

 `{your moodle}/webservice/rest/server.php?wstoken=xxxxx&wsfunction=local_aspiredu_get_courses&moodlewsrestformat=json&options[ids][0]=1&options[ids][1]=2&page=0&perpage=2`

Thank you.

**Comment by tim-schilling** [comment]
Confirmed. Thank you, will update after testing.

**Comment by tim-schilling** [comment]
@guillogo what's the returned ordering for this and would it be possible for us to miss a element due to a new course or change to the field that the ordering is based on that would result in a page's contents changing?

**Comment by guillogo** [comment]
Hi @tim-schilling I've added now a new param to sort by any course field (by default is the course id). Also, by default it will return 100 items if perpage is not set.

**sort example call:**
`{your moodle}//webservice/rest/server.php?wstoken=064f37c4fc7753531f9f1320325b94ff&wsfunction=local_aspiredu_get_courses&moodlewsrestformat=json&page=0&perpage=10&sort=shortname` 


Thank you.

**Comment by tim-schilling** [comment]
How can I find out which fields have indexes on them at the database level? We don't want to rely on sorting by something that there isn't an index for.

**Comment by guillogo** [comment]
hi @tim-schilling you can find the indexes in the Moodle repo here: https://github.com/moodle/moodle/blob/master/lib/db/install.xml#L112 (for master moodle master branch) you can change the branch to check but I'd say this hasn't change since at least 3.8
