### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by tim-schilling** [aspiredu/moodle-local_aspiredu#26]
It looks like our CI is setup for Moodle 3.11 rather than the more modern versions of moodle. @andrewhancox is that something you can address?

**Comment by andrewhancox** [comment]
Am working on this now. Should he done tomorrow morning.Sent from my iPhoneOn 13 Nov 2023, at 19:12, Tim Schilling ***@***.***> wrote:﻿
Assigned #26 to @andrewhancox.
