### ISSUE TITLE
Create a privacy/provider class

### ISSUE THREAD

**Issue by guillogo** [aspiredu/moodle-local_aspiredu#9]
Hi, I've created this issue to implement the privacy/provider class for this plugin. Thank you.

**Comment by guillogo** [comment]
Update: Privacy API has been implemented in dev. However, it'll require Tim's validation.

**Comment by tim-schilling** [comment]
@guillogo What should I be validating? Is there anything that you're particularly unsure regarding our integration that I need to double check for us?

Do the empty functions need to be populated or are they effectively stubs because we aren't implementing them?

**Comment by guillogo** [comment]
Hi @tim-schilling 

You just need to check if there is more information in your plugin that you consider private data in addition to these: https://github.com/aspiredu/moodle-local_aspiredu/blob/dev/classes/privacy/provider.php#L48 if not, everything is done for issue #9.

About the empty functions, they are fine like that, and we are declaring those just in case we need them in the future. 

cheers

**Comment by tim-schilling** [comment]
Looks good.
